-- Script generated by Redgate Compare v1.18.2.12220
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating pgaudit...';END$$;
CREATE EXTENSION pgaudit WITH SCHEMA public VERSION '1.7';


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating pg_stat_monitor...';END$$;
CREATE EXTENSION pg_stat_monitor WITH SCHEMA public VERSION '2.0';

SET check_function_bodies = true;
