CREATE TABLE employee
(
    employeeid   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname    VARCHAR(50),
    lastname     VARCHAR(50),
    email        VARCHAR(100),
    phone        VARCHAR(20),
    address      TEXT,
    departmentid INTEGER,
    position     VARCHAR(50),
    joiningdate  date,
    salary       numeric(10, 2),
    CONSTRAINT employee_pkey PRIMARY KEY (employeeid)
);