CREATE TABLE department
(
    departmentid   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    departmentname VARCHAR(50),
    managerid      INTEGER,
    CONSTRAINT department_pkey PRIMARY KEY (departmentid)
);